//
// Created by bertr on 13-12-25.
//

#ifndef TESTCOLLISION_CONTROLLERLEVELTUTORIAL2_H
#define TESTCOLLISION_CONTROLLERLEVELTUTORIAL2_H


class ControllerLevelTutorial2 {
};


#endif //TESTCOLLISION_CONTROLLERLEVELTUTORIAL2_H